name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workspace/miage-portfolio
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: workspace/miage-portfolio/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          OWNER_LOWER=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          if [[ "$REPO_NAME" == "${OWNER_LOWER}.github.io" ]]; then
            BASE_PATH="/"
          else
            BASE_PATH="/$REPO_NAME/"
          fi
          echo "Using Vite base: $BASE_PATH"
          npm run build -- --base=$BASE_PATH

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: workspace/miage-portfolio/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

